source "http://rubygems.org"
group :development do
gem 'compass'            # Depends on Sass, will be installed automatically.
gem 'compass-960-plugin' # 960.gs
gem 'compass-validator'  # So you can `compass validate`.
gem 'rb-inotify', '~> 0.8.8'
gem 'oily_png'           # Faster Compass sprite generation.
gem 'css_parser'         # Helps `compass stats` output statistics.
gem 'guard-compass'      # Compile on sass/scss change.
gem 'guard-livereload'   # Browser reload.
gem 'yajl-ruby'          # Faster JSON with LiveReload in the browser.
end
